---
new_page_extension: md
auto_deploy: false
admin_path: "/public/admin"
webhook_url: 
sections:
- type: directory
  path: content/posts
  label: Posts
  create: documents
  match: "*.md"
  new_doc_ext: md
  templates:
  - posts
- type: directory
  path: content/authors
  label: Authors
  create: documents
  match: "*.md"
  exclude: _index.md
  new_doc_ext: md
  templates:
  - authors
- type: heading
  label: Pages
- type: document
  path: content/about.md
  label: About
- type: document
  path: content/contact.md
  label: Contact
- type: document
  path: content/404.md
  label: '404'
- type: document
  path: content/privacy-policy.md
  label: 'Privacy Policy '
- type: document
  path: content/elements.md
  label: Elements
- type: heading
  label: Settings
- type: document
  path: config/config.json
  label: Config
- type: document
  path: config/menu.json
  label: Menu
  match: "**/*"
- type: document
  path: config/social.json
  label: Social
  match: "**/*"
- type: document
  path: config/theme.json
  label: Theme
  match: "**/*"
upload_dir: public/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: ".vuepress/dist"
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
